name: 'Build LaTex Document'
on: [push, pull-request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install CJK fonts 
      run: sudo apt update -qq && sudo apt-get install -y fonts-noto-cjk-extra && sudo fc-cache -fv
    - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile TeX to PDF
      run: tectonic main.tex
