name: 'Build LaTex Document'
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Download CJK fonts 
      run: |
        mkdir -p ~/.local/share/fonts
        wget -nc -P ~/.local/share/fonts -i fonts.txt
        fc-cache -fv
    - uses: actions/cache@v2.1.4
      name: Tectonic Cache
      with:
        path: |
          ~/.cache/Tectonic
          ~/.local/share/fonts
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
           ${{ runner.os }}-tectonic-
    - uses: wtfjoke/setup-tectonic@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile TeX to PDF
      run: tectonic main.tex
